routes/catalog.py
from flask import Blueprint
from flask import flash
from flask import jsonify
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for

from models import Item
from models import User
from utils import token
from utils import signed_in

Catalog = Blueprint('catalog', __name__)


@Catalog.route('/')
@Catalog.route('/catalog')
@Catalog.route('/catalog.<type>')
def full_catalog(type='html'):
    """Lists out categories and latest items.

    Accepts GET method.
    Does not require authentication.
    If the optional type parameter is set and is equal to JSON,
    return a JSON response with all catalog items
    """
    categories = Item.get_categories()
    latest = Item.get_latest(10)
    if type.lower() == 'json':
        catalog = dict()
        for category in categories:
            category_items = Item.by_category(category)
            catalog[category] = [i.serialize for i in category_items]
        return jsonify(catalog=catalog)
    return render_template(
        'catalog-full.html',
        categories=categories,
        latest=latest)


@Catalog.route('/catalog/add', methods=['GET', 'POST'])
def create_item():
    """Add an item.

    Accepts GET and POST methods.
    Redirect if user is not signed in.

    """
    if not signed_in():
        flash('You must be logged in to add an item.')
        return redirect(url_for('catalog.full_catalog'))

    if request.method == 'POST':
        name = request.form.get('name')
        description = request.form.get('description')
        category = request.form.get('category')
        csrftoken = request.form.get('csrftoken')
        if csrftoken != session['csrf']:
            flash('Invalid CSRF token.')
        elif not name or not description or not category:
            flash('All fields must be filled.')
        else:
            # Everything valid. Create item.
            del session['csrf']
            item = Item.create_item(name, description,
                                    category, session['user_id'])
            if item:
                flash('Item successfully updated.')
                return redirect(url_for(
                    'catalog.show_item',
                    category_name=item.category,
                    item_name=item.name))
    categories = Item.get_categories()
    session['csrf'] = token()
    return render_template('catalog-add.html', categories=categories)


@Catalog.route('/catalog/<category_name>')
@Catalog.route('/catalog/<category_name>.<type>')
def list_category(category_name, type='html'):
    """Lists the items of a category.

    Accepts GET method.
    Does not require authentication.
    If the optional type parameter is set and is equal to JSON,
    return a JSON response with all items with category=category_name.

    Parameters:
        category_name: category name of items to search for
    """
    categories = Item.get_categories()
    category_items = Item.by_category(category_name)

    if type.lower() == 'json':
        return jsonify(category_items=[i.serialize for i in category_items])
    return render_template(
        'catalog-category.html',
        categories=categories,
        category_items=category_items)


@Catalog.route('/catalog/<category_name>/<item_name>')
@Catalog.route('/catalog/<category_name>/<item_name>.<type>')
def show_item(category_name, item_name, type='html'):
    """Show description of item.

    Accepts GET method.
    Does not require authentication.
    If the optional type parameter is set and is equal to JSON,
    return a JSON response with item=item_name with category=category_name.

    Parameters:
        category_name: category name of item
        item_name: name of the item
    """

    item = Item.by_name(category_name, item_name)
    if not item:
        flash('Could not find item: {}.'.format(item_name))
        return redirect('/')

    categories = Item.get_categories()
    category_items = Item.by_category(category_name)
    if type.lower() == 'json':
        return jsonify(item=item.serialize)
    return render_template('catalog-item.html',
                           item=item,
                           categories=categories,
                           category_items=category_items)


@Catalog.route(
    '/catalog/<category_name>/<item_name>/edit', methods=['GET', 'POST'])
def edit_item(category_name, item_name):
    """Edit an item.

    Accepts GET and POST methods.
    Redirect to show_item page if user is not authenticated/authorized.

    Parameters:
        category_name: category name of item to edit
        item_name: name of the item to edit
    """
    item = Item.by_name(category_name, item_name)
    if not item:
        flash('Could not find item: {}.'.format(item_name))
        return redirect('/')

    if not signed_in():
        flash('You must be logged in to edit an item.')
        return redirect(url_for(
            'catalog.show_item',
            category_name=item.category,
            tem_name=item.name))

    if not item.is_owned_by(session['user_id']):
        flash('You do not have permission to edit this item.')
        return redirect(url_for(
            'catalog.show_item',
            category_name=item.category,
            item_name=item.name))

    if request.method == 'POST':
        name = request.form.get('name')
        description = request.form.get('description')
        category = request.form.get('category')
        csrftoken = request.form.get('csrftoken')
        if csrftoken != session['csrf']:
            flash('Invalid CSRF token.')
        elif not name or not description or not category:
            flash('All fields must be filled.')
        else:
            del session['csrf']
            item.name = name
            item.description = description
            item.category = category
            flash('Item successfully updated.')
            return redirect(url_for(
                'catalog.show_item',
                category_name=item.category,
                item_name=item.name))

    categories = Item.get_categories()
    category_items = Item.by_category(category_name)
    session['csrf'] = token()
    return render_template(
        'catalog-item-edit.html',
        item=item,
        categories=categories,
        category_items=category_items)


@Catalog.route(
    '/catalog/<category_name>/<item_name>/delete', methods=['GET', 'POST'])
def delete_item(category_name, item_name):
    """Delete an item.

    Accepts GET and POST methods.
    Redirect to show_item page if user is not authenticated/authorized.

    Parameters:
        category_name: category name of item to delete
        item_name: name of the item to delete
    """
    item = Item.by_name(category_name, item_name)
    if not item:
        flash('Could not find item: {}.'.format(item_name))
        return redirect('/')

    if not signed_in():
        flash('You must be logged in to delete an item.')
        return redirect(url_for(
            'catalog.show_item',
            category_name=item.category,
            item_name=item.name))

    if not item.is_owned_by(session['user_id']):
        flash('You do not have permission to delete this item.')
        return redirect(url_for(
            'catalog.show_item',
            category_name=item.category,
            item_name=item.name))

    if request.method == 'POST':
        csrftoken = request.form.get('csrftoken')
        if csrftoken != session['csrf']:
            flash('Invalid CSRF token.')
        else:
            del session['csrf']
            item.delete()
            flash('Item successfully deleted.')
            return redirect('/')

    categories = Item.get_categories()
    category_items = Item.by_category(category_name)
    session['csrf'] = token()
    return render_template(
        'catalog-item-delete.html',
        item=item,
        categories=categories,
        category_items=category_items)

routes/users.py
from flask import Blueprint
from flask import flash
from flask import make_response
from flask import render_template
from flask import session
from flask import request
from flask import redirect
from flask import url_for
import json
from oauth2client import client
from oauth2client import crypt

from models import User
from utils import token
import config

Users_bp = Blueprint('users', __name__, template_folder='templates')


@Users_bp.route('/login')
def login():
    """Log the user in."""
    session['csrf'] = token()
    return render_template('login.html')


@Users_bp.route('/token', methods=['POST'])
def verify_token():
    """Verifies the identify of the user through their oauth token

    Returns a 200 HTTP response if the token is valid
    Returns a 401 HTTP response on error.
    """
    token = request.form.get('token')
    csrftoken = request.form.get('csrftoken')
    provider = request.form.get('provider')

    if csrftoken != session['csrf']:
        response = make_response(json.dumps('Invalid CSRF token.'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response
    session['csrf'] = ''
    try:
        token_info = client.verify_id_token(
            token, config.oauth['google']['client_id'])
        if token_info['iss'] not in ['accounts.google.com',
                                     'https://accounts.google.com']:
            raise crypt.AppIdentityError("Wrong issuer.")
        session['provider'] = 'google'
        session['name'] = token_info['name']
        session['email'] = token_info['email']
        user = User.by_email(token_info['email']) or User.create_user(session)
        session['user_id'] = user.id
        response = make_response(json.dumps('You have logged in.'),
                                 200)
        response.headers['Content-Type'] = 'application/json'
        return response
    except crypt.AppIdentityError:
        response = make_response(json.dumps('Invalid token.'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response


@Users_bp.route('/logout')
def logout():
    """Log the user out."""
    if 'user_id' in session:
        del session['provider']
        del session['user_id']
        del session['name']
        del session['email']
    flash('You have successfully been logged out.')
    return redirect('/')

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="/css/styles.css">
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="/js/scripts.js"></script>
        <meta name="google-signin-client_id" content="973180597680-9k6ckf48l1iotcgcl9bhr2jen2tuuv54.apps.googleusercontent.com">
        <script src="https://apis.google.com/js/client:platform.js?onload=signout" async defer></script>

        {% block scripts %}
        {% endblock %}
        <title>Item Catalog</title>
    </head>
    <body>
        <div class="container">
            <header class="row">
                {% include "header.html" %}
            </header>
            <main class="row">
                <div class='col-md-12 flash'>
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <ul>
                        {% for message in messages %}
                        <li> <strong> {{ message }} </strong> </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                {% endwith %}
                </div>
                {% block content %}
                {% endblock %}
            </main>
        </div>
    </body>
</html>

templates/catalog-add.html
{% extends "base.html" %}
{% block content %}
<section class="col-md-3">
{% include "catalog-category-list.html" %}
</section>
<section class="col-md-9">
<h2>Add an Item</h2>
<form method="post">
    <input type="hidden" name="csrftoken" value="{{ session['csrf'] }}">
    <div class="form-group">
        <label for="name">Item Name:</label>
        <input class="form-control" type="text" name="name" id="name">
    </div>
    <div class="form-group">
        <label for="description">Item Description:</label>
        <textarea class="form-control" name="description" id="description"></textarea>
    </div>
    <div class="form-group">
        <label for="category">Category:</label>
        <input class="form-control" type="text" name="category" id="category">
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Submit</button>
    </div>
</form>
</section>
{% endblock %}

templates/catalog-category-item-list.html
<h2 class="text-capitalize">{{ category_items[0].category }}</h2>
<ul class="list-unstyled">
{% for item in category_items %}
<li><a href="{{ url_for('catalog.show_item',category_name=item.category,item_name=item.name) }}">{{ item.name }}</a></li>
{% endfor %}
</ul>

templates/catalog-category-list.html
<h2>Categories</h2>
<ul class="text-capitalize list-unstyled"">
{% for category in categories %}
<li><a href="{{ url_for('catalog.list_category',category_name=category) }}">{{ category }}</a></li>
{% endfor %}
</ul>

templates/catalog-category.html
{% extends "base.html" %}
{% block content %}
<section class="col-md-3">
{% include "catalog-category-list.html" %}
</section>
<section class="col-md-3">
{% include "catalog-category-item-list.html" %}
</section>
{% endblock %}

templates/catalog-full.html
{% extends "base.html" %}
{% block content %}
<section class="col-md-3">
{% include "catalog-category-list.html" %}
</section>
<section class="col-md-9">
<h2>Latest additions</h2>
<ul>
{% for item in latest %}
<li><a href="{{ url_for('catalog.show_item',category_name=item.category,item_name=item.name) }}">{{ item.name }}</a> (<a href="{{ url_for('catalog.list_category',category_name=item.category) }}" class="text-capitalize">{{item.category}}</a>)</li>
{% endfor %}
</ul>
</section>
{% endblock %}

templates/catalog-item-delete.html
{% extends "base.html" %}
{% block content %}
<section class="col-md-3">
{% include "catalog-category-list.html" %}
</section>
<section class="col-md-3">
{% include "catalog-category-item-list.html" %}
</section>
<section class="col-md-6">
<h2>Delete {{ item.name }}</h2>
<p>Are you sure you want to delete this item?</p>
<h3>{{ item.name }}</h3>
<p>{{ item.description }}</p>
<form method="post">
    <input type="hidden" name="csrftoken" value="{{ session['csrf'] }}">
    <div class="form-group">
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{{ url_for('catalog.show_item',category_name=item.category,item_name=item.name) }}" class="btn btn-default">Cancel</a>
    </div>
</form>
</section>
{% endblock %}

templates/catalog-item-edit.html
{% extends "base.html" %}
{% block content %}
<section class="col-md-3">
{% include "catalog-category-list.html" %}
</section>
<section class="col-md-3">
{% include "catalog-category-item-list.html" %}
</section>
<section class="col-md-6">
<h2>Edit {{ item.name }}</h2>
<form method="post">
    <input type="hidden" name="csrftoken" value="{{ session['csrf'] }}">
    <div class="form-group">
        <label for="name">Item Name:</label>
        <input class="form-control" type="text" name="name" id="name" value="{{ item.name }}">
    </div>
    <div class="form-group">
        <label for="description">Item Description:</label>
        <textarea class="form-control" name="description" id="description">{{ item.description }}</textarea>
    <div class="form-group">
        <label for="category">Category:</label>
        <input class="form-control" type="text" name="category" id="category" value="{{ item.category }}">
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-success btn-sm">Submit</button>
        <a href="{{ url_for('catalog.show_item',category_name=item.category,item_name=item.name) }}" class="btn btn-danger btn-sm">Cancel</a>
    </div>
</form>
</section>
{% endblock %}

templates/catalog-item.html
{% extends "base.html" %}
{% block content %}
<section class="col-md-3">
{% include "catalog-category-list.html" %}
</section>
<section class="col-md-3">
{% include "catalog-category-item-list.html" %}
</section>
<section class="col-md-6">
<h2>{{ item.name }}</h2>
<p>{{ item.description }}</p>
{% if signed_in() and item.is_owned_by(session['user_id']) %}
<ul class="nav navbar-nav">
<li><a href="{{ url_for('catalog.edit_item',category_name=item.category,item_name=item.name) }}">Edit</a></li>
<li><a href="{{ url_for('catalog.delete_item',category_name=item.category,item_name=item.name) }}">Delete</a></li>
</ul>
{% endif %}
</section>
{% endblock %}

templates/debug.html
{{ session }}
<br>
{{ request }}
<br>
{{ request.form }}
<br>
{{ request.args }}
<br>

templates/header.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Item Catalog</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/">Latest</a></li>
      {% if signed_in() %}
      <li><a href="{{ url_for('catalog.create_item') }}">Add an Item</a></li>
      {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
    {% if signed_in() %}
        <li><a href="{{ url_for('users.logout') }}" class=".logout"><span class="glyphicon glyphicon-log-out"> Logout</span></a></li>
    {% else %}
        <li><a href="{{ url_for('users.login') }}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
    </ul>
    {% if signed_in() %}
        <p class="navbar-text navbar-right">Welcome, {{ session['name'] }}!</p>
    {% endif %}
    
  </div>
</nav>

templates/login.html
{% extends "base.html" %}
{% block content %}
<section class="col-md-12">
<h3>Login with one of the following providers:</h3>
<div id="g-btn" data-onsuccess="onSignIn"></div>
<div class="g-signin2" data-onsuccess="onSignIn" data-onload="false"></div>
<script>
function onSignIn(googleUser) {
  var id_token = googleUser.getAuthResponse().id_token;
  qs = 'token=' + id_token + '&csrftoken={{ session.csrf }}&provider=google';
  $.ajax({
    type: 'POST',
    url: '/token',
    data: {
      'token': id_token,
      'csrftoken': '{{session.csrf}}',
      'provider': 'google'
    },
    statusCode: {
      200: function() {
        $('#result').html('Logged in using Google credentials! Redirecting. . .')
          setTimeout(function() {
              window.location.href = "/";
          }, 3000);
        },
      401: function() {
        $('#result').html('Failed to login.');
          signOut();
      }

    }
      });
  }
</script>
<div id="result"></div>
</section>
{% endblock %}
{% block scripts %}
{% endblock %}